version: '3'

services:

  birthday-service:
    image: birthday-service:latest
    env_file:
      - ./app.env
    ports:
      - 8000:8000
      
  api-gateway:
    image: api-gateway:latest
    env_file:
      - ./app.env
    ports:
      - 9000:9000
    depends_on:
      - birthday-service

  birthday-ui:
    build: .
    ports:
      - 80:80
    depends_on:
      - api-gateway
    